spring.application.name=pawwatch-users
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.tkuaxlkxfknebwsxdizr
spring.datasource.password=Xoriano073110!@


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
logging.level.org.springframework.web=DEBUG